### ISSUE TITLE
Update to QEMU 4.2.0

### ISSUE THREAD

**Issue by XVilka** [avatartwo/avatar-qemu#4]
QEMU 4.2.0 will be released very soon, with a lot of improvements since 3.1.0 you use.

See the [full Changelog](https://wiki.qemu.org/ChangeLog/4.2), especially the [TCG Plugins](https://wiki.qemu.org/Features/TCGPlugins) feature.

**Comment by mariusmue** [comment]
That's a very good call! Normally, I'm trying to do the rebase annualy in the beginning of a year, but the TCG Plugins features sounds very useful. I'll look into this once I have free cycles ;)

**Comment by mariusmue** [comment]
With v1.3.1 of avatar, avatar-qemu is officially based on Qemu v4.2.0-rc5
